repos:
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.4.3
  hooks:
  - id: autopep8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
  - id: flake8
    exclude: ^docs/
